### ISSUE TITLE
Hardcrash when declaring a function

### ISSUE THREAD

**Issue by Niomi0** [jtwm-0677/Basic-10-Download#4]
On 2.6 if you attempt to declare a function it will hard crash, if you attempt to load the script from backup it will crash on startup.

**Comment by Niomi0** [comment]
Also happens with 'sub'

**Comment by jtwm-0677** [comment]
Fixed in commit 4162b6c. Added try-catch wrapper around error checking and infinite loop protection in parser for FUNCTION, SUB, FOR, WHILE, and DO blocks. The app will no longer crash when declaring these keywords.

**Comment by Niomi0** [comment]
Issue still present in 2.6.3. Trying to create a select case causes a crash. Should be reopened.
